import type { Metadata } from "next"
import { Poppins, Montserrat, Roboto } from "next/font/google"
import "./globals.css"
import HeroUiProvider from "./provider/herouiProvider"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-montserrat",
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${poppins.variable} ${montserrat.variable} ${roboto.variable} h-screen w-full`}
      >
        <HeroUiProvider>{children}</HeroUiProvider>
      </body>
    </html>
  )
}
